### PR TITLE
issue#25: added disableStackPeaks property processing

### PR DESCRIPTION
**Pull request by vrepetenko**

### CODE REVIEW

**Review by PhilippHaefele — COMMENTED** [review]
The done changes look good.

How do the different views (with and without `waend`) look like, when peak analysis is disabled. We do show `----` instead of the normal unavailable values which shows `??? %`. This allows the user and us to easily determine that the setting is on (peak detection disabled)

**Comment by vrepetenko** [comment]
there are with/without screenshots:

Screenshot 2023-02-21 at 22 51 03

Screenshot 2023-02-21 at 22 55 56

**Comment by PhilippHaefele** [comment]
Ok seems reasonable for me

**Comment by haneefdm** [comment]
Thanks you all.

**Pull request merged**
