### PR TITLE
Feature/basic ci

### PR DESCRIPTION
**Pull request by PhilippHaefele**

### CODE REVIEW

**Review by haneefdm — APPROVED** [review]
Maybe we should add vsce to our package.json so we don't have to install during CI separately.

**Comment by PhilippHaefele** [comment]
> Maybe we should add vsce to our package.json so we don't have to install during CI separately.

Yes had this in mind from svd-viewer. Also was thinking about using yarn. As i have never used it, i need to check what the pros are etc.

Also will have a look into the solution, i have posted some time ago in a Cortex-Debug issue for creating (pre-) releases.

**Comment by PhilippHaefele** [comment]
> I tried `yarn` because I inherited it. I had to put in several workarounds and did not work as expected. I know most people are migrating to yarn.
> 
> 
> 
> Also, yarn's local cache had gotten me into trouble...until I found it had a cache and I have to clean it to get certain things working. Was very frustrating.
> 
> 
> 
> For packages our size, yarn's speed advantage (due to parallel installs), I doubt helps in any major way.
> 
> 
> 
> So, lets stay with npm for now.

Ok perfect so i do not need to make anything regarding this.

Will still add vsce to the package.json and remove the installation from the ci job

**Comment by haneefdm** [comment]
> Will still add vsce to the package.json and remove the installation from the ci job

Yes, when you have the time.

@PhilippHaefele  Btw, how is everything with you? I don't want to put anything private here. Let's call it your project that was due in early Feb. You know my email from my github profile, so you can send an update if you wish.

**Pull request merged**
